language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
# env:
#   - MONGO_VERSION=2.4.3

# services: mongodb

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install nmap -qq"
install:
  - "pip install flake8"
  # - "pip install boto" # disabled: since boto not supporting py3
  # - "pip install pymongo sqlalchemy MySQL-python" # disabled MySQL-python (not py3 compatible)
  # - "pip install pymongo sqlalchemy pymysql"
  - "pip install coveralls"
  - "pip install ."
before_script:
  - "flake8 . --exclude test,docs,examples"
  # - mysql -e 'create database poulet;'
script: nosetests --with-coverage --cover-package=libnmap
after_success:
  coveralls
deploy:
  on:
    tags: true
  provider: pypi
  user: savon_noir
  password:
    secure: WiMQsq+IMzAsS+cNKyKT7u7PlwGwkH0t2eoBitP0ckIw6kNWlbM/HCCm6aa9Ns9LpIzI82x26Vg77bu+yiMxUzZPS8pxCJXL9fFGs7Qc6VC9S0iHUX+FCkhFEFvPl35YRGFuY0YQyF2oj9vZPPFFmXzY2JSOBHxVevgdsrw1BQM=